# Repo Agents Configuration

# Default Claude model for all agents
claude:
  model: claude-4-5-sonnet
  max_tokens: 4096
  temperature: 0.7

# Repository settings
repository:
  # Directory containing agent markdown files
  agents_dir: .github/claude-agents

  # Directory for generated workflows
  workflows_dir: .github/workflows

# Security settings
security:
  # Require all agents to have explicit outputs
  require_outputs: true

  # Require all agents to have explicit permissions
  require_permissions: true
