name: Bug Report
description: Report a bug or unexpected behavior in Repo Agents
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us investigate.

        <!--
        AI AGENT INSTRUCTIONS:
        When filing a bug report, follow these guidelines:

        1. TITLE: Use format "[Bug]: <concise description>" - be specific, not generic
           Good: "[Bug]: Parser fails on multiline YAML strings in frontmatter"
           Bad: "[Bug]: It doesn't work"

        2. DESCRIPTION: Include the exact error message, what you were trying to do,
           and the specific behavior observed. Quote error messages verbatim.

        3. EXPECTED BEHAVIOR: Describe what should have happened based on documentation
           or reasonable expectations.

        4. STEPS TO REPRODUCE: Provide minimal, complete steps. Include exact commands
           and file contents needed to reproduce. Someone should be able to copy-paste
           these steps and see the same issue.

        5. AGENT DEFINITION: Always include a minimal reproducible example if the bug
           involves agent parsing or workflow generation. Strip out unrelated config.

        6. ERROR OUTPUT: Include the FULL error message and stack trace, not just
           the first line. Use the exact output, don't paraphrase.

        7. CATEGORY: Choose based on where the error occurs:
           - Parser Error: YAML/frontmatter parsing, schema validation
           - Generator Error: Workflow YAML generation
           - CLI Error: Command-line interface issues
           - Workflow Runtime Error: Issues when workflow runs in GitHub Actions
           - Output Handler Error: Problems with add-comment, create-pr, etc.

        8. ENVIRONMENT: Always include Bun version (bun --version), OS with version,
           and repo-agents version. These are critical for reproduction.

        9. CONTRIBUTION: Check this if you've identified a fix or are willing to investigate.
        -->

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? Be as specific as possible.
      placeholder: "When I run `repo-agents compile`, I get..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: "I expected the workflow to..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide numbered steps to reproduce the issue.
      placeholder: |
        1. Create an agent file with...
        2. Run `repo-agents compile`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: agent-definition
    attributes:
      label: Agent Definition
      description: If applicable, paste your agent markdown file (or relevant parts).
      render: yaml
      placeholder: |
        ---
        name: my-agent
        on:
          issues:
            types: [opened]
        outputs:
          - add-comment
        ---

        Agent instructions here...
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Paste any error messages, logs, or stack traces.
      render: shell
      placeholder: |
        Error: Invalid agent definition
          at parseAgent (src/parser/index.ts:42)
          ...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which part of Repo Agents is affected?
      options:
        - Parser Error
        - Generator Error
        - CLI Error
        - Workflow Runtime Error
        - Output Handler Error
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide your environment details.
      placeholder: |
        - Bun version: 1.x.x
        - OS: macOS 14.x / Ubuntu 22.04 / Windows 11
        - repo-agents version: x.x.x
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help fix this bug?
      options:
        - label: I would be willing to submit a PR to fix this bug
