import type { OutputConfig } from '../../types/index';
import type { OutputHandler, RuntimeContext } from './base';

class AddCommentHandler implements OutputHandler {
  name = 'add-comment' as const;

  getContextScript(_runtime: RuntimeContext): string | null {
    // No dynamic context needed for add-comment
    return null;
  }

  generateSkill(config: OutputConfig): string {
    const maxConstraint = config.max || 'unlimited';

    return `## Skill: Add Comment

Add a comment to the current issue or pull request.

**File to create**: \`/tmp/outputs/add-comment.json\`

For multiple comments, use numbered suffixes: \`add-comment-1.json\`, \`add-comment-2.json\`, etc.

**JSON Schema**:
\`\`\`json
{
  "body": "string"
}
\`\`\`

**Fields**:
- \`body\` (required): Markdown-formatted comment text

**Constraints**:
- Maximum comments: ${maxConstraint}
- Body must be non-empty

**Example**:
Create \`/tmp/outputs/add-comment.json\` with:
\`\`\`json
{
  "body": "Thank you for reporting this issue! I've analyzed it and added appropriate labels."
}
\`\`\`

Or for multiple comments:
- \`/tmp/outputs/add-comment-1.json\`
- \`/tmp/outputs/add-comment-2.json\`

**Important**: Use the Write tool to create this file. Only create the file when you're ready to post the comment.`;
  }

  generateValidationScript(config: OutputConfig, runtime: RuntimeContext): string {
    const issueOrPrNumber = runtime.issueOrPrNumber;
    const maxConstraint = config.max;

    return `
# Validate and execute add-comment output(s)
COMMENT_FILES=$(find /tmp/outputs -name "add-comment*.json" 2>/dev/null || true)

if [ -n "$COMMENT_FILES" ]; then
  # Count files
  FILE_COUNT=$(echo "$COMMENT_FILES" | wc -l)
  echo "Found $FILE_COUNT add-comment output file(s)"

  # Check max constraint
  ${
    maxConstraint
      ? `
  if [ "$FILE_COUNT" -gt ${maxConstraint} ]; then
    echo "- **add-comment**: Too many comment files ($FILE_COUNT). Maximum allowed: ${maxConstraint}" > /tmp/validation-errors/add-comment.txt
    exit 0
  fi`
      : ''
  }

  # Phase 1: Validate all files
  VALIDATION_FAILED=false
  for comment_file in $COMMENT_FILES; do
    echo "Validating $comment_file..."

    # Validate JSON structure
    if ! jq empty "$comment_file" 2>/dev/null; then
      echo "- **add-comment**: Invalid JSON format in $comment_file" >> /tmp/validation-errors/add-comment.txt
      VALIDATION_FAILED=true
      continue
    fi

    # Extract body
    COMMENT_BODY=$(jq -r '.body' "$comment_file")

    # Validate body is non-empty
    if [ -z "$COMMENT_BODY" ] || [ "$COMMENT_BODY" = "null" ]; then
      echo "- **add-comment**: Comment body is empty or missing in $comment_file" >> /tmp/validation-errors/add-comment.txt
      VALIDATION_FAILED=true
      continue
    elif [ \${#COMMENT_BODY} -gt 65536 ]; then
      echo "- **add-comment**: Comment body exceeds 65536 characters in $comment_file" >> /tmp/validation-errors/add-comment.txt
      VALIDATION_FAILED=true
      continue
    fi

    echo "✓ Validation passed for $comment_file"
  done

  # Check if we have an issue/PR number
  ISSUE_NUMBER="${issueOrPrNumber}"
  if [ -z "$ISSUE_NUMBER" ]; then
    echo "- **add-comment**: No issue or PR number available" >> /tmp/validation-errors/add-comment.txt
    VALIDATION_FAILED=true
  fi

  # Phase 2: Execute only if all validations passed
  if [ "$VALIDATION_FAILED" = false ]; then
    echo "✓ All add-comment validations passed - executing..."
    for comment_file in $COMMENT_FILES; do
      COMMENT_BODY=$(jq -r '.body' "$comment_file")

      # Append footer with workflow and job information
      FOOTER="\\n\\n---\\n\\n*Generated by workflow [\${{ github.workflow }}](\${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }})*"
      COMMENT_BODY_WITH_FOOTER="$COMMENT_BODY$FOOTER"

      # Add comment via GitHub API
      gh api "repos/${runtime.repository}/issues/$ISSUE_NUMBER/comments" \\
        -f body="$COMMENT_BODY_WITH_FOOTER" || {
        echo "- **add-comment**: Failed to post comment from $comment_file via GitHub API" >> /tmp/validation-errors/add-comment.txt
      }
    done
  else
    echo "✗ add-comment validation failed - skipping execution (atomic operation)"
  fi
fi
`;
  }
}

// Export handler for registration
export const addCommentHandler = new AddCommentHandler();
